language: generic

sudo: false

notifications:
    email: false

branches:
    only:
        - master
        # Regex to build tagged commits with version numbers
        - /\d+\.\d+(\.\d+)?(-\S*)?$/

os:
    - linux

env:
    global:
        - COVERAGE=false
        - CONDA_PREFIX=/home/travis/miniconda3

    # Build under all combinations of the of the following
    matrix:
        - PYTHON=3.5
        - PYTHON=3.6 COVERAGE=true

before_install:
    # Get Miniconda from Continuum
    # Need to source the script to set the PATH variable in this environment
    # (not the scripts environment)
    - source ci/install-miniconda.sh
    - conda update --yes conda
    # Install dependencies
    - conda install --yes python=$PYTHON pip -c conda-forge
    - conda install --yes --file requirements.txt -c conda-forge
    - conda install --yes --file requirements-dev.txt -c conda-forge
    # Install dependencies
    - if [ "$COVERAGE" == "true" ]; then pip install coveralls==0.5; fi
    # Show installed pkg information for postmortem diagnostic
    - conda list

install:
    # Package and install
    - python setup.py bdist_wheel
    - pip install dist/*

script:
    # Run the test suite
    - if [ "$COVERAGE" == "true" ]; then make coverage; else make test; fi
    # Check code for PEP8 style and lint for code quality
    - make pep8
    - make lint

after_success:
    - if [ "$COVERAGE" == "true" ]; then coveralls; fi
