name: gmt-python
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - pip
    - numpy
    - matplotlib
    - pytest
    - pytest-cov
    - pytest-mpl
    - flake8
    - pylint
    - coverage
    - sphinx
    - nbsphinx
    - jupyter
    - numpydoc
    - twine
    - fftw
    - gdal
    - ghostscript
    - libnetcdf
    - hdf5=1.8.18.*
    - zlib
    - blas
    - curl
    - pcre
