name: gmt-python
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.6
    - pip
    - numpy
    - matplotlib
    - pytest
    - pytest-cov
    - flake8
    - pylint
    - coverage
    - sphinx
    - sphinx-gallery
    - numpydoc
    - jupyter
    - twine
